language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

#================================

before_install:
  - chmod +x gradlew
  - sudo apt update
  - sudo apt install ocl-icd-opencl-dev
  - sudo apt-get -qq update

script:
  - chmod +x gradlew
  - ./gradlew test --info
  - ./gradlew check
  - ./gradlew codeCoverageReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
